### ISSUE TITLE
Recaptcha.getClient(siteKey:) always returns an error

### ISSUE THREAD

**Issue by dimitris-c** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#14] opened 2022-11-22 18:14 UTC
**Describe the bug**

Intergrated the latest version `18.0.2`.
Using the following
```
Recaptcha.getClient(siteKey: siteKey) { [weak self] client, error in
            if let error {
                print("RecaptchaClient creation error: \(error).")
            }
            if let client {
                self?.recaptchaClient = client
            }
        }
```

I always get an `RecaptchaClient creation error: Error code: 100.` 
Didn't have this issue with previous versions.

Also wrapping the above code as per instructions on https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps crashes the app, see screenshot below for the crash.

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [x] SPM
* [ ] Cocoapods
* [ ] Direct Download

**SDK Version (e.g. 18.0.1):** 18.0.2

**To Reproduce**

Simulator & Device seems to always fail when using `Recaptcha.getClient(siteKey:)`

A crash occurs when trying to use ` Task { ... await Recaptcha.getClient(siteKey:) ... }`

**Expected behavior**

Should be able to get the client from `Recaptcha.getClient`

**Screenshots**
Screenshot of the crash
![tmp](https://user-images.githubusercontent.com/886854/203389193-5dc38869-b12b-41c9-a329-bf80f777dfa8.png)

**Xcode version (please complete the following information):**
 - Version [e.g. Xcode 13.4.1]

**Device (please complete the following information):**
 - Model: [e.g. iPhone6] iPhone 14 Simulator - Device: iPhone XS Max
 - OS: [e.g. iOS8.1] iOS 16 Simulator - Device iOS 1.5.
 - Simulator or real Device? Simulator & Device

**Additional context**

-

**Comment by mcorner** [comment] 2022-11-22 20:57
We are looking into this, thank you for the bug report.

**Comment by Andrewviski** [comment] 2022-11-24 18:48
We have investigated this locally and were able to reproduce, it was an internal issue with the SDK that happen on low end devices/emulators. A release with the fix is coming soon 

Thanks for filing the bug! 😄

**Comment by leszko11-heetch** [comment] 2022-11-25 12:36
Hi there 👋 
I'm receiving same error `RecaptchaClient creation error: Error code: 100.` for all 18.0.X versions now.

Verified using [this](https://github.com/leszko11-heetch/recaptcha-poc) project

**Comment by mcorner** [comment] 2022-11-28 14:23
We are targeting a release of a fix this week, thank you for the bug report.

**Comment by mcorner** [comment] 2022-11-30 21:52
18.0.3 just went out with a probable fix for this.  Let us know if this works (but note there is a scoring bug ATM: #16)

**Comment by leszko11-heetch** [comment] 2022-11-30 22:52
Thanks @mcorner for the update. I did a quick test and I successfully received `RecaptchaToken` object, but I spot another bug. I had no bundle ID specified in Google Cloud Console and disabled bundle ID verification, but still sdk returned error 4 `Invalid Package Name.` After specifying bundle ID in Console it works as expected. Do you want me to file another issue?

**Comment by mcorner** [comment] 2022-12-01 01:37
@leszko11-heetch Thanks for testing!  And yes, we already have a fix for the allow all bundles that will go to production Friday of next week. 

However.....we don't recommend using it. Please read the warning on this page: https://developers.google.com/recaptcha/docs/domain_validation

**Comment by dimitris-c** [comment] 2022-12-01 12:45
@mcorner Nice thanks for the quick fix, will integrate and report back 👍

**Comment by bjjeong** [comment] 2022-12-01 21:17
I'm receiving the same error as OP but `18.0.3` does not fix the issue for me. Tested on:
- iOS Simulator (iPhone 14 Pro)
- Integrated via direct download

**Comment by mcorner** [comment] 2022-12-01 21:43
If you downloaded it via direct download, that is very likely to be 18.0.2 as we haven't updated the direct download link yet (takes longer than pushing to cocoapods). Also note that direct download nomlonger requires protobuf as a dependency (it is included now).  Lmk if I am wrong.

**Comment by bjjeong** [comment] 2022-12-01 22:20
@mcorner I pretty much took the link from the documentation and manually changed the version number in the URL. https://dl.google.com/recaptchaenterprise/v18.0.3/RecaptchaEnterprise_iOS_xcframework/recaptcha-xcframework.xcframework.zip

> Also note that direct download no longer requires protobuf as a dependency (it is included now). Lmk if I am wrong.

do you mean it's no longer a dependency in version `18.0.2` or `18.0.3`?

**Comment by mcorner** [comment] 2022-12-01 22:31
Can you try a real device?   Also, send me your sitekey at markcorner at the company I work at...

And in 18.0.3 you no longer need protobuf as a dependency.  18.0.2 you did

**Comment by bjjeong** [comment] 2022-12-01 22:36
I've tried on a real device (iPhone 14 Pro) as well. Just sent you and email as well.

> And in 18.0.3 you no longer need protobuf as a dependency. 18.0.2 you did

understood!

**Comment by mcorner** [comment] 2022-12-02 15:26
@bjjeong I believe I have a minimal reproduction of your error.  I want to confirm that you aren't actually getting a 100  you are getting a crash, right?

I get this while using RN with by bridging from objc to a swift use of reCAPTCHA.  Oddly it is working while using it directly from objc in RN.  You can give that a try to see what you get.

I think this is a) a different issue and b) is RN related.  We don't really support RN ATM, but I want to see if we can fix this.  I get some indications that this might be related to #15 actually.

**Comment by bjjeong** [comment] 2022-12-02 16:14
@mcorner yep, no 100 error, just a crash.

that's interesting because the first approach I tried was with objc and I was getting the same error. To confirm, when you got it to work with objc, were you on `18.0.3` or `18.0.2`?

I'll give objc another try right now - perhaps I did something wrong the first time.

**Comment by mcorner** [comment] 2022-12-02 16:53
Ok, this is definitely a different bug, opened #18

**Comment by bjjeong** [comment] 2022-12-02 17:22
@mcorner good news - I was able to get it to work with both objc and swift.

Thank you for pointing out #15. That issue reminded me that in my logs, I kept getting the following warning `Main Thread Checker: UI API called on a background thread: -[WKWebView .cxx_construct]`.

To get this to work, I had to make sure the calls to `getClient` and `execute` were being called on the main thread.

For swift:
```swift
@objc
func initialize(_ siteKey: String) {
  DispatchQueue.main.async { // <------- this right here
    Recaptcha.getClient(siteKey: siteKey) { [weak self] client, error in
      if let error {
        print("RecaptchaClient creation error: \(error).")
      }
      if let client {
        self?.recaptchaClient = client
      }
    }
  }
}
```

For objc:
```objc
RCT_EXPORT_METHOD(initialize:(NSString *)siteKey)
{
  dispatch_async(dispatch_get_main_queue(), ^{
    [Recaptcha getClientWithSiteKey:siteKey
          completionHandler:^void(RecaptchaClient* recaptchaClient, RecaptchaError* error) {
            if (!recaptchaClient) {
              NSLog(@"%@", error);
              return;
            }
            NSLog(@"reCAPTCHA initialized!");
          }
    ];
  });
}
```

After wrapping those calls, both `getClient` and `execute` complete with no issues!

**Comment by mcorner** [comment] 2022-12-02 17:56
Great! Yes further discussion in #18. 

I am closing this issue since the original issue is likely solved.  Please open a new issue if not.

**Closed by mcorner** 2022-12-02 17:56 UTC
Labels: bug
