### ISSUE TITLE
Crash on Recaptcha.getClient method execution

### ISSUE THREAD

**Issue by tetokasane** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#35] opened 2023-02-09 01:58 UTC
**Describe the bug**

There is a crash in my app, it occurs during Recaptcha client initialization

<img width="1394" alt="Снимок экрана 2023-02-09 в 04 35 22" src="https://user-images.githubusercontent.com/48354683/217697275-204a5fcd-f24c-46ce-97a0-e874cb38e9ef.png">
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCAx_GPBTimestamp initWithTimeIntervalSince1970:]: unrecognized selector sent to instance 0x2831fd380'
terminating with uncaught exception of type NSException

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [x] SPM (iOS)
* [ ] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1): 18.1.0**

**To Reproduce**

1. Initialize the SDK with Recaptcha.getClient method

**Expected behavior**

Recaptcha client initializes without any crashes, completionHandler executes after initialization

**Screenshots**

**Screenshot of Xcode window with crash details provided

**Xcode version for iOS (please complete the following information):**
 - Version 14.2

**Device (please complete the following information):**
 - Model: iPhone 11
 - OS: iOS 16.3
 - A real device(Also tried simulator with iOS 15.6.1, got same error)

**Comment by mcorner** [comment] 2023-02-09 11:32
Duplicate of #20 need -ObjC

**Closed** 2023-03-03 19:49 UTC
Labels: bug

**Comment by mcorner** [comment] 2023-12-14 21:57
Note that -ObjC is no longer required as of 18.4.0
