### ISSUE TITLE
[Bug]: PlatformException(FL_INIT_FAILED, com.google.android.recaptcha.RecaptchaException: Internal Error, null, null)

### ISSUE THREAD

**Issue by YuWenHaoqq** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#60] opened 2023-07-06 02:43 UTC
### Are you seeing the problem on Android or iOS?

None

### Contact Details

yuwenhaomail@gmail.com

### Describe the bug

This error may occur on individual networks and phones

### Select the method used to integrate with reCAPTCHA Mobile.

SPM (iOS)

### SDK Version

18.2.1

### To Reproduce

RecaptchaEnterprise.initClient can throw exception when open app

### To Reproduce

- Model: readmi 9a
- OS: miui 12.0.6
- real Device

### Relevant log output

```shell
I/flutter (18313): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (18313): PlatformException(FL_INIT_FAILED, com.google.android.recaptcha.RecaptchaException: Internal Error, null, null)
I/flutter (18313): 
I/flutter (18313): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
I/flutter (18313): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
I/flutter (18313): <asynchronous suspension>
I/flutter (18313): #2      MethodChannelRecaptchaEnterprise.initClient (package:recaptcha_enterprise_flutter/recaptcha_enterprise_method_channel.dart:34:12)
I/flutter (18313): <asynchronous suspension>
I/flutter (18313): #3      initRecaptchaEnterprise (package:coupert/main.dart:278:5)
I/flutter (18313): <asynchronous suspension>
I/flutter (18313): ----------------------------------------------------
```

### Relevant log output

This issue may occur when using the company intranet and cannot be replicated on other networks
Sorry, we can only provide this information. For whatever reason, I don't have any direction either

**Comment by YuWenHaoqq** [comment] 2023-07-06 02:49
Of course, this intranet can access Google services

**Comment by mcorner** [comment] 2023-07-06 09:53
Excellent.  This exception comes from Flutter, but is due to an underlying issue in the SDK.  I *believe* this is related to a hostname difference in China.  Fixing it will require an SDK update.  Give us a few weeks and I think we can sort this out.

It would be really great if you would be willing to privately beta test something in your own environment for me.  Email me at my first name and lastname @google.com and I can send youa build.

Internal bug reference: b/290170911

**Comment by mcorner** [comment] 2023-07-07 18:04
I do have a possible fix in a beta build if someone wants to try it.  Also verify that you can reach the following two URLs:

https://www.gstatic.cn/images/branding/product/1x/avatar_pages_square_blue_32dp.png
https://www.gstatic.com/images/branding/product/1x/avatar_pages_square_blue_32dp.png

**Comment by YuWenHaoqq** [comment] 2023-07-10 03:59
https://www.gstatic.cn/images/branding/product/1x/avatar_pages_square_blue_32dp.png
https://www.gstatic.com/images/branding/product/1x/avatar_pages_square_blue_32dp.png

I am able to successfully access both addresses
my email:yuwenhaomail@gmail.com
If you can give me the address of the test package, I am willing to test

**Comment by aBenVip** [comment] 2023-07-10 10:50
[INFO:CONSOLE(1)] "Uncaught ReferenceError: recaptcha is not defined", source: https://www.recaptcha.net/recaptcha/api3/mwv 
this log happened when init recaptcha sdk

**Comment by mcorner** [comment] 2023-07-12 12:15
Update: we are working internally first to see if we can verify the problem and fix. Thanks for your patience.

**Comment by YuWenHaoqq** [comment] 2023-07-13 05:55
OK, I will check the latest situation every day. If there is a package that can be tested, please tell me where it is. Thank you 🙏

**Comment by mcorner** [comment] 2023-07-21 13:46
We have confirmed the fix by testing behind the firewall in China.  We are now waiting for another internal fix to release.  I would expect to see this in 18.3.0

**Comment by thetanz-geoff** [comment] 2023-08-08 00:57
Thanks @mcorner. Very eager to see this go live as soon as it can.

**Comment by thetanz-geoff** [comment] 2023-08-16 01:59
Hello again @mcorner. Could you please advise whether this fix is on-track to be released this week?

**Comment by mcorner** [comment] 2023-08-18 17:35
Android and iOS 18.3.0 have been released with a fix for this issue.

**Closed by mcorner** 2023-08-18 17:35 UTC
Labels: bug

**Comment by thetanz-geoff** [comment] 2023-08-27 01:49
Much appreciated @mcorner.

**Comment by gastsail** [comment] 2023-10-27 13:39
This internal error happens also on Android in the 18.2.0 , is this mandatory to update it to 18.3.0 ? This is because I want to know if that internal error is also fixed for every platform using the latest version.

We need to migrate different modules in the company to 1.9.0 in order to update this dependency and we need to know if its a good choice to migrate to this latest version

**Comment by mcorner** [comment] 2023-10-27 14:46
The forced Kotlin upgrade is an unfortunate side effect, we have looked into alternatives, but Google follows the Kotlin releases very, very quickly.

But yes, you have to be on at least 18.3.0 to fix the issue in China.

There are other sources of internal errors, but those are getting stamped out over time from the backend.

**Comment by gastsail** [comment] 2023-10-27 15:56
Great @mcorner , we are on Argentina, but I think that upgrading our modules to kotlin 1.9 will be the best for future updates, because new updates of recaptcha will require kotlin 1.9.0 , that's right ? 

Thanks !

**Comment by gastsail** [comment] 2023-10-30 17:25
So, can we use kotlin 1.8.0 with gradle 8.0 and JDK 19 to upgrade to 18.3 , right ?

Because instead of migrating to kotlin 1.9.0 , our team will have less effort upgrading to kotlin 1.8.0 to upgrade recaptcha to 18.3.0 

Let me know about this so we can start working on it, thanks a lot @mcorner

**Comment by mcorner** [comment] 2023-11-01 11:02
I don't believe we have tested all of the combinations of jdk and gradle versions, but I don't see why it wouldn't work. You can always try a small test app first to confirm.

**Comment by alqayyim** [comment] 2023-11-09 14:07
@mcorner Hi, it's still happening on 18.3.0

![image](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/14579168/1de33b91-38bc-4c7d-9d23-a3518fbfb660)

**Comment by mcorner** [comment] 2023-11-09 14:23
Can you post a text version of this stack trace?

**Comment by mcorner** [comment] 2023-11-09 14:24
And open a new bug, I see you are not using this in China so this is not related to the original issue.

**Comment by saseungmin** [comment] 2026-02-24 04:28
@mcorner 

Sorry to keep asking, but I think this is a fairly important point for our adoption — you mentioned the SDK works as long as `recaptcha.net` is accessible. I couldn't find any configuration for this in the documentation. Does the SDK automatically route requests through `recaptcha.net` by default, or is there any additional setup needed on our end?
