### ISSUE TITLE
[Error: Initialize client first] when using Recaptcha.fetchClient

### ISSUE THREAD

**Issue by gyulhana** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#131] opened 2024-12-05 05:44 UTC
I am a React Native developer currently integrating your package into our app. I followed the installation steps and usage guidelines provided in the readme.md file.

The documentation suggests using initClient and execute. But Based on the code of the package,
```
/**
 * Initialize a reCAPTCHA client
 * @deprecated Use {@link Recaptcha.fetchClient} instead
 * @param siteKey Your application's reCAPTCHA site key
 * @param timeout An optional timeout value in milliseconds
 */
export function initClient(siteKey: string, timeout?: number): Promise<string> {
  let args: Args = {};

  if (timeout) {
    args.timeout = timeout;
  }

  return RecaptchaEnterpriseReactNative.initClient(siteKey, args);
}

/**
 * Execute reCAPTCHA and retrieve a token
 * @deprecated Use {@link RecaptchaClient.execute} instead
 * @param action An action to describe what the user is doing such as "login"
 * @param timeout An optional timeout value in milliseconds
 */
export function execute(
  action: RecaptchaAction,
  timeout?: number
): Promise<string> {
  let args: Args = {};

  if (timeout) {
    args.timeout = timeout;
  }

  return RecaptchaEnterpriseReactNative.execute(action.action, args);
}
```
 these methods are deprecated. So I implemented the following code:
```
      try {
        await initClient(siteKey);

        // Step 1
        const client = Recaptcha.fetchClient(siteKey);

        // Step 2
        const token = await client.execute({ action: 'kkr_recaptcha' });

        // set the result
        setInitResult('ok');
        setExecuteResult(token);
        console.log(token);
      } catch (error) {
        // error exception
        console.log(error);
        setInitResult(error?.toString());
        setExecuteResult(error?.toString());
      }
```
However, when I execute the code, I encounter the following error:

[Error: Initialize client first]

This seems to suggest that the client must be explicitly initialized, but initClient is marked as deprecated. Could you clarify how to properly initialize the client with the latest version of the package?

Additionally, I would like to know where I can find up-to-date documentation for the most recent version of this package.

Environment:
	•	React Native version: 0.76.1
	•	Package version: 18.6.0
	•	Platform: iOS/Android

Thank you for your assistance! Looking forward to your guidance.

**Comment by walterjgsp** [comment] 2024-12-05 14:00
Thanks for the issue @gyulhana. The two methods can't be used interchangeable. So if you call `initClient` you can't call the `execute` from `Recaptcha.fetchClient`. If you remove the first call `await initClient(siteKey);` it should work. 

I was able to reproduce this behavior you faced by calling the deprecated mode in the example app we have in the React Native repository and calling execute on the new one.

**Comment by gyulhana** [comment] 2024-12-05 14:10
@walterjgsp oh, sorry. It seems like there was a misunderstanding. Initially, I only used fetchClient without calling initClient, but I encountered the error [Error: Initialize client first]. So, I added initClient, and it was working. but since this method is deprecated, I'm unsure how to proceed. Could you provide an example using a non-deprecated approach?

**Comment by walterjgsp** [comment] 2024-12-05 14:31
@gyulhana, I tested from my side and this seems to be working. Use the import:

```
import {
  Recaptcha,
  RecaptchaAction,
  type RecaptchaClient,
} from '@google-cloud/recaptcha-enterprise-react-native';
```

We create some states to update the UI:

```
const [recaptchaClient, setRecaptchaClient] =
    React.useState<RecaptchaClient>();
  const [initResult, setInitResult] = React.useState<string>('Not Initialized');
  const [executeResult, setExecuteResult] = React.useState<
    string | undefined
  >();
  const [token, setToken] = React.useState<string | undefined>();
```

And the buttons to initialize the client and fetch the token:

```
<View style={styles.container}>
      <Button
        onPress={() => {
          try {
            setRecaptchaClient(Recaptcha.fetchClient(siteKey ?? 'SITEKEY'));
            setInitResult('ok');
          } catch (error: any) {
            setInitResult(error.toString());
          }
        }}
        title="Fetch Client"
        testID="fetchClientButtonId"
      />
      <Text>Fetch Client Result: </Text>
      <Text testID="fetchClientResultId">{initResult}</Text>

      <Button
        onPress={() => {
          if (recaptchaClient) {
            recaptchaClient
              .execute(RecaptchaAction.LOGIN(), 10000)
              .then((newToken) => {
                setExecuteResult(newToken.startsWith('03') ? 'ok' : 'error');
                setToken(newToken);
              })
              .catch((error) => {
                setExecuteResult(error.toString());
              });
          } else {
            setExecuteResult('Recaptcha Client is undefined');
          }
        }}
        title="Execute"
        testID="clientExecuteButtonId"
      />
      <Text>Execute Result:</Text>
      <Text testID="clientExecuteResultId">{executeResult}</Text>
      <Text>Token:</Text>
      <Text testID="tokenId">{token}</Text>
    </View>
```

We will update the documentation to exemplify how to use the new API. Please let me know if this works for you. If not could you provide a small reproduction of your code in a repository so we can test?

**Comment by walterjgsp** [comment] 2024-12-05 15:24
I've actually found the issue with your code by checking the difference on it. There's a bug on how the RN wrapper for reCAPTCHA is working in the current `fetchClient` API. We do not wait in the wrapper for the client to be initialized and return immediately so you can execute and fetch token. Since there's no wait for the state in `fetchClient` if you can `execute` right way the error you're facing will be triggered. In the next release we will fix this issue and also update the documentation. Thanks @gyulhana !

**Comment by walterjgsp** [comment] 2024-12-10 14:50
@gyulhana, a new version of the RN SDK was released and should include the changes to fix the `fetchClient` API and better documentation. Closing this bug for now, please open it again in case it doesn't work for you.

**Closed by walterjgsp** 2024-12-10 14:50 UTC
Labels: bug

**Comment by gyulhana** [comment] 2024-12-11 01:09
@walterjgsp thx!
