### ISSUE TITLE
iOS crash on initializer

### ISSUE THREAD

**Issue by hammadqayyum** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#36] opened 2023-02-13 09:32 UTC
sdk crashes on getClient()
when using version 18.1.0 using all three methods (SPM, cocoa and Direct Download)
let (recaptchaClient, error) = Recaptcha.getClient(
          siteKey: "reCAPTCHA_KEY_iOS")
When downgrading to 18.0.0 using package manager everything works fine.

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ *] SPM (iOS)
* [* ] Cocoapods (iOS)
* [* ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.1.0):**

**To Reproduce**

call Recaptcha.getClient()

**Expected behavior**

**Screenshots**
Attached

**Xcode version for iOS (please complete the following information):**
 - Version 14.1 (14B47b)

**Device (please complete the following information):**
 - Simulator & Real Device Both (iOS 16.1 , iOS 15.4)
 - Emulator/Simulator or real Device? 
![Screenshot 2023-02-13 at 2 24 39 PM](https://user-images.githubusercontent.com/9613274/218421334-07666c13-263a-4929-a20d-2b9491cb412c.png)

**Additional context**

**Comment by mcorner** [comment] 2023-02-13 11:14
Duplicate of #20   missing -ObjC

**Closed by mcorner** 2023-02-13 11:14 UTC
Labels: bug

**Comment by hammadqayyum** [comment] 2023-02-13 11:59
Yup that fixed the issue . Thanks and sorry i missed the latest thread . I got this issue a week ago and it was not posted i guess at that time

**Comment by mcorner** [comment] 2023-12-14 21:57
Note that -ObjC is no longer required as of 18.4.0
